name: ci

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 24
          - 25
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Maven Install
        run: ./mvnw install -B -V -DskipTests -Dair.check.skip-all
      - name: Maven Tests
        run: ./mvnw install -B -P ci
